### ISSUE TITLE
Add file upload option to contracts

### ISSUE THREAD

**Issue by mzambrano-tc** [nautobot/nautobot-app-device-lifecycle-mgmt#158]
### Environment
* Nautobot version:  1.5.12
* nautobot-plugin-device-lifecycle-mgmt version:  1.1.2

Contracts should also include a "File Attachment" field. This should allow users to upload files (purchases orders, quotes, etc)  to nautobot.
 
### Proposed Functionality

This could use the Django filed FileField and the upload_to to save the files to the MEDIA_ROOT.

### Use Case
This allows users to attach documents related to the contracts, like purchases orders, quotes, shipping packing lists, etc

**Comment by mzambrano-tc** [comment]
@progala  Any update about this feature?

**Comment by progala** [comment]
@mzambrano-tc we discussed this internally and we are considering adding a new URL field to the model that could be used to record location, such as S3 bucket, where the artifacts are stored.

Storing arbitrary files directly on the Nautobot server is usually not recommended. This is due to the difficulty in applying access permissions, additional overhead involved in serving the files, and it being tricky to manage files in HA deployments with multiple Nautobot instances.
